spring.application.name=harmoGestionWeb
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
server.port=${HARMOGESTION_WEB_PORT}
fr.afpa.cda19.harmogestionweb.api-url=http://${HARMOGESTION_API_HOST}:${HARMOGESTION_API_PORT}